# can use variables like {build} and {branch}
version: 1.3.{build}
pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - master

configuration:
  - Debug
  - Release

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      VS_VERSION_MAJOR: 12
      BOOST_ROOT: C:\Libraries\boost_1_58_0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VERSION_MAJOR: 14
      BOOST_ROOT: C:\Libraries\boost_1_60_0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_VERSION_MAJOR: 15
      BOOST_ROOT: C:\Libraries\boost_1_66_0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      VS_VERSION_MAJOR: 16
      BOOST_ROOT: C:\Libraries\boost_1_73_0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      VS_VERSION_MAJOR: 17
      BOOST_ROOT: C:\Libraries\boost_1_73_0

matrix:
  exclude:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      platform: Win32
    
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      platform: Win32

platform:
  - Win32
  - x64

before_build: "scripts\\appveyor.bat"

build:
  parallel: true
  project: build/cereal.sln
  verbosity: minimal

test_script: "scripts\\appveyor.bat test"

artifacts:
  - path: build\Testing
  - path: out
